sonar.projectKey=bompellithilak-cpu_retail-dq-pipeline-poc
sonar.projectName=Retail DQ Pipeline POC
sonar.projectVersion=1.0.0
sonar.organization=bompellithilak-cpu

sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
